### ISSUE TITLE
v2.2.1 - Broken on SSR due to window undefined

### ISSUE THREAD

**Issue by jonluca** [cedricdelpoux/react-responsive-masonry#120]
![CleanShot 2024-06-28 at 11 43 23@2x](https://github.com/cedricdelpoux/react-responsive-masonry/assets/13029040/539a5135-56f7-4dac-bda2-f116c8c05506)

It looks like GitHub does not have the latest version of the source code, but v2.2.1 broke SSR by having an unprotected window call during render

**Comment by NawarA** [comment]
would love to see a fix on this too! 

breaking our next.js app

**Comment by DanielWahl** [comment]
Same here.

**Comment by tygrxqt** [comment]
It broke some of my apps too. The two workarounds I found were either to render the component on the client, or the package version needs to be downgraded to `2.2.0`.

**Comment by cedricdelpoux** [comment]
Can you checkout v`2.3.0`? It should resolve the issue

**Comment by NawarA** [comment]
> Can you checkout v`2.3.0`? It should resolve the issue

Thank you so much for the patch, checking now...

Looks like the SSR error is gone 🥳 

Quick question: looks like `ResponsiveMasonry` initially renders with 1 column, and then it kicks in and respects `columnsCountBreakPoints`. This creates a Layout Shift, which dings a website's/PWA's SEO score (see Chrome Lighthouse or this [article](https://web.dev/articles/cls)).

Is it possible to have `ResponsiveMasonry` initially render using the values in `columnsCountBreakPoints`, instead of defaulting to 1 initially?

**Comment by cedricdelpoux** [comment]
It could be great! PR's are welcome if you want to help :)
